### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: tech/mappie/api/Mappie when trying to compile for iOS (compileKotlinIosSimulatorArm64)

### ISSUE THREAD

**Issue by lkjh654** [Mr-Mappie/mappie#161]
**Describe the bug**
Library configured according to the readme file. Version 0.10.0 was used, when trying to compile for iOS using `compileKotlinIosSimulatorArm64` task compilation fails with:
```
e: java.lang.NoClassDefFoundError: tech/mappie/api/Mappie
        at tech.mappie.preprocessing.ProjectMappieDefinitionsCollector.visitClass(DefinitionsCollector.kt:80)
        at tech.mappie.preprocessing.ProjectMappieDefinitionsCollector.visitClass(DefinitionsCollector.kt:69)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
        at tech.mappie.util.BaseVisitor.accept(BaseVisitor.kt:15)
        at tech.mappie.preprocessing.ProjectMappieDefinitionsCollector.visitFile(DefinitionsCollector.kt:75)
        at tech.mappie.preprocessing.ProjectMappieDefinitionsCollector.visitFile(DefinitionsCollector.kt:69)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:28)
        at tech.mappie.util.BaseVisitor.accept(BaseVisitor.kt:15)
        at tech.mappie.preprocessing.ProjectMappieDefinitionsCollector.visitModuleFragment(DefinitionsCollector.kt:72)
        at tech.mappie.preprocessing.ProjectMappieDefinitionsCollector.visitModuleFragment(DefinitionsCollector.kt:69)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:33)
        at tech.mappie.preprocessing.DefinitionsCollector.collect(DefinitionsCollector.kt:22)
        at tech.mappie.MappieIrRegistrar.generate$lambda$4(MappieIrRegistrar.kt:31)
        at tech.mappie.MappieIrRegistrar.handleMappieProblems(MappieIrRegistrar.kt:55)
        at tech.mappie.MappieIrRegistrar.generate(MappieIrRegistrar.kt:30)
```

**To Reproduce**
try to run `compileKotlinIosSimulatorArm64` task for KMP project

**Expected behavior**
Compilation tasks is successful 

**Additional context**
The library works fine on Android. The dependency was added in: `commonMain.dependencies {}` block. Compiler version: 2.1.0.

**Comment by stefankoppier** [comment]
Hi @lkjh654, thanks for the report. I do not have a mac, so it is hard for me to reproduce. 

I do have a strong suspicion that this is fixed in the master branch, in which it is no longer required to explicitly add the mappie-api dependency. I will add an explicit error message, instead of a generic exception for when this problem occurs.

I will create a release for `1.0.0`, can you give that version a try when it's released?

**Comment by lkjh654** [comment]
I will! :)

**Comment by stefankoppier** [comment]
After some trouble with JReleaser, I managed to release 1.0.0

**Comment by lkjh654** [comment]
After bumping version to 1.0.0 I'm getting another exception during compilation for iOS:
```
e: Compilation failed: While analysing /XXX/KoinModule.kt:12:29: java.lang.NoClassDefFoundError: tech/mappie/api/config/UseStrictVisibility
```
It still works fine on Android

**Comment by lkjh654** [comment]
Adding `tech.mappie:mappie-api:1.0.0` to `iosMain.dependencies` changes nothing - there is still a compilation error (the same one as above).

**Comment by stefankoppier** [comment]
HI @lkjh654. The issue is fixed. It is planned for release 1.1.0.

 I wasn't able to reproduce for ios but mingwx64 had the same issue. If an issue remains on ios, please re-open this ticket.

**Comment by lkjh654** [comment]
Thanks for the update! When is the 1.1.0 release planned? I'd like to test the fix.

**Comment by stefankoppier** [comment]
@lkjh654 I just made a release 🙂
